---
- name: Install system etckeeper package
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - etckeeper
    - git-core # Explicitly specify git to ensure we install in "git-mode"
  become: yes
