---
- name: Install NodeJS packages
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - nodejs
    - npm
  become: yes
- name: Create node modules directory
  file:
    path: "{{ node_modules_directory }}"
    state: directory
- name: Install JS development packages
  npm:
    path: "{{ node_modules_directory }}"
    name:
    - eslint
    - eslint-plugin-vue
    - js-beautify
    state: present
