export PYENV_VERSION="{{ pyenv_version }}"
export PYENV_ROOT="{{ pyenv_root }}"
export PYENV_VERSIONS_ROOT="{{ pyenv_versions_root }}"

export PYTHON2_VERSION="{{ python2_version }}"
export PYTHON2_ROOT_DIRECTORY="{{ python2_root_directory }}"
export PYTHON2_BIN_DIRECTORY="{{ python2_bin_directory }}"
export PYTHON2_LIB_DIRECTORY="{{ python2_lib_directory }}"
export PYTHON2_CONFIG_DIRECTORY="{{ python2_config_directory }}"

export PYTHON3_VERSION="{{ python3_version }}"
export PYTHON3_ROOT_DIRECTORY="{{ python3_root_directory }}"
export PYTHON3_BIN_DIRECTORY="{{ python3_bin_directory }}"
export PYTHON3_LIB_DIRECTORY="{{ python3_lib_directory }}"
export PYTHON3_CONFIG_DIRECTORY="{{ python3_config_directory }}"
