---
- name: Install user tools
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - avahi-autoipd
    - avahi-daemon
    - cryptsetup
    - firefox
    - gnome-tweak-tool
    - gparted
    - htop
    - i3
    - ifstat
    - lm-sensors
    - nmap
    - openssh-client
    - screen
    - stow
    - sysstat
    - tree
    - wdiff
    - xclip
  become: yes
